# ---- Variables de la app ----
JORNADA_ACTUAL = "J2"
SHEET_URL = "https://docs.google.com/spreadsheets/d/1Ig_Dm_HTjmZoTxVI4Dec6QfA62Ble9J0CMRs8kQgtHk/edit?gid=0#gid=0"
SHEET_ENTRADAS = "Entradas"

[partidos]
Nimi_rival = "Vallekas Walker"       # iMaccabi
Armando_rival = "Nottingham Miedo"   # InterM

# ---- Credenciales del Service Account ----
[gcp_service_account]
type = "service_account"
project_id = "nimble-volt-466016-e2"
private_key_id = "05072d7c6fcef8ff4cc1fd05cbabfc4523ee28d4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDqvZsoEbv9ZhNc
VdeOmsTNjMe0ymnoJSu7c6RgGeE7UX8yso3XSH521kDBAzOLhcp/tYQklKBIN923
tId5mIoT8/cS2wA98KnCs+JOaYSMtT5IwPZcNkxFhrjZw0AAoDOVV3NaXguERaV/
LJHNVC/+a8cMO3r6I+Ml31yvZ0gKTbukfU1fcIMPR2ro3Ah8+M+I+gue53U4cGIg
IgJjKgWed/yVqfCjplEtNB8PP3NOIW+TkBwIZjBSrIPpBhtrVYJLEuA9gkesugJe
IiNqTfyKHSv8xG/UgtrxPtgCauNX0V0Rptgww88gpAmM4buMyfwoQ+5nAsisE7Z3
GHkT3CcFAgMBAAECggEATmLPV3OIl4cJCwndR9D1y//pRj1bXTpgXqGwr6ikthay
R38pb0zVciB8khdcFIiyRLAb9s0sssD5CFm/7YJbBWuvwzufWo+tWIeSGAYTTZtO
N6Q8ADHfiU4CFzGkgzD72LBRpEkIRnytVYjQDUVCG47o8nRAThxCw0hRnn76JvoH
Za44ZGjBbYlsNBMQUOTM2eMc4TC8bCdNkNw4DAvXbA8owuCRauNWLC2CUhKV6ggA
gDrYO0+8D9CIPbQ5CCmUWk4Sjyx2OyoHu7IkZLsmJlMGD1qBgC9LwZ2jv23kCS2J
kPFR+0FAJ+7Puut7W0g4eitAOCYb1ltTsz6E39P+pwKBgQD4S9UybOnb304l+L1C
SAfaqQgyOdNfHia31u2b/E0WgMLsw4B43R04rGH51294The6C3sBci9nLcZd+8v4
F9V0SSQe1lBWckTuR8mXWXgNIlaJb3kRoeljVkozpXYoeKia1wNwp6WI8B5H+t93
lR27ZlD5HXlk5PWpxg6ayoMu1wKBgQDyBhqkqG435C4BgxOFsy0rAQnEnbS/hdud
o4UXpLdg8sIH6C9fLnSitleI/8T8FjBLOa4NgEB3lLAOljstJFbd3eAHkcBYpxvs
0LFkBRiyHvwGZNY9ZRVn5W5FclCC2aqPa4TPTkOXVDr26NVHSVuHh8v3BQrX5uv1
gvbbqANpgwKBgQDTIyEDBSyD5Mq+bVr6rufG36/xjcyY+Lmx4Jki6JPgy9N1o/Vu
UZBUrfmOi8zlP3rboIGTxDZdBcbGCqTyrcm8XanScynTqM3G1dKt2c3FVWrC6cDI
5qbg6vKkIlJsrdWp/aaWOGkCHjWRvdojBPFIdwPqIk8lJbFlEd8/b2/H9wKBgE8O
72UaH+biAqU7zATAouCJVkeDvKdTconsAG3YwI5KvlcW4WKWKkN8jNuTsSUnml74
WILQgj6Ns3UQXgRA+p8++w997PcIn3acNVYW1BpbRLhR+CnV+0gVChBlZydXMv/m
f1u4lRu5yAkfxYujyuJa2aW3X/Nm2203eqwGFhdBAoGBAM3MktdYXZW0C1nH0SOx
9fO5lRaS2YzsGZh/E9HIajJmgafC884WQQi6m/qH+JGOOgtiFs49MkwVZJ8Jv4ZX
Z+bYpDZlWRK+Z45tL9hl/BtC9pjha0BlzL8PqgSmAGBJCaFHgr6vnWPyQPzvBT6u
DE5GTpLddWgy9iapzj29I+cG
-----END PRIVATE KEY-----"""
client_email = "fantasy-streamlit@nimble-volt-466016-e2.iam.gserviceaccount.com"
client_id = "117990085686883720044"
token_uri = "https://oauth2.googleapis.com/token"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fantasy-streamlit%40nimble-volt-466016-e2.iam.gserviceaccount.com"
